// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class RoombookinginvaliddataTest
{
    private IWebDriver driver;
    public IDictionary<string, object> vars { get; private set; }
    private IJavaScriptExecutor js;
    [SetUp]
    public void SetUp()
    {
        driver = new ChromeDriver();
        js = (IJavaScriptExecutor)driver;
        vars = new Dictionary<string, object>();
    }
    [TearDown]
    protected void TearDown()
    {
        driver.Quit();
    }
    [Test]
    public void roombookinginvaliddata()
    {
        driver.Navigate().GoToUrl("https://automationintesting.online/");
        driver.Manage().Window.Size = new System.Drawing.Size(516, 672);
        driver.FindElement(By.CssSelector(".btn:nth-child(5)")).Click();
        js.ExecuteScript("window.scrollTo(0,2204)");
        {
            var element = driver.FindElement(By.CssSelector(".rbc-month-row:nth-child(5) .rbc-row:nth-child(2)"));
            Actions builder = new Actions(driver);
            builder.MoveToElement(element).ClickAndHold().Perform();
        }
        {
            var element = driver.FindElement(By.CssSelector(".rbc-month-row:nth-child(5) .rbc-row:nth-child(2)"));
            Actions builder = new Actions(driver);
            builder.MoveToElement(element).Perform();
        }
        {
            var element = driver.FindElement(By.CssSelector(".rbc-month-row:nth-child(5) .rbc-row:nth-child(2)"));
            Actions builder = new Actions(driver);
            builder.MoveToElement(element).Release().Perform();
        }
        driver.FindElement(By.CssSelector(".rbc-month-row:nth-child(5) .rbc-row:nth-child(2)")).Click();
        driver.FindElement(By.Name("lastname")).Click();
        driver.FindElement(By.Name("lastname")).Click();
        driver.FindElement(By.Name("lastname")).SendKeys("Test123");
        driver.FindElement(By.Name("email")).Click();
        driver.FindElement(By.Name("email")).SendKeys("test123@gmail.com");
        driver.FindElement(By.Name("phone")).Click();
        driver.FindElement(By.Name("phone")).SendKeys("55555555123");
        driver.FindElement(By.CssSelector(".btn:nth-child(6)")).Click();
        {
            var element = driver.FindElement(By.CssSelector(".btn:nth-child(6)"));
            Actions builder = new Actions(driver);
            builder.MoveToElement(element).Perform();
        }
        {
            var element = driver.FindElement(By.tagName("body"));
            Actions builder = new Actions(driver);
            builder.MoveToElement(element, 0, 0).Perform();
        }
        driver.Close();
    }
}
